version: "3.8"

services:
  haproxy:
    build: ./haproxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
      - mobile

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: ./backend/.env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mobile:
    build: ./mobile
    ports:
      - "8081:8081"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
